/**
 * Central Error Code Registry
 * Phase B3.2 - Error Standardization
 */

module.exports = {
    // Core Domain Errors
    AUTH_REQUIRED: 'AUTH_REQUIRED',               // 401
    FORBIDDEN: 'FORBIDDEN',                       // 403
    FILING_LOCKED: 'FILING_LOCKED',               // 423
    COMPUTATION_REQUIRED: 'COMPUTATION_REQUIRED', // 422
    VALIDATION_FAILED: 'VALIDATION_FAILED',       // 422
    PAN_NOT_VERIFIED: 'PAN_NOT_VERIFIED',         // 403
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION', // 409
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',     // 404
    INTERNAL_ERROR: 'INTERNAL_ERROR',             // 500

    // JSON / ERI / Integration
    JSON_GENERATION_FAILED: 'JSON_GENERATION_FAILED', // 500
    ERI_REJECTED: 'ERI_REJECTED',                 // 422
    ERI_TIMEOUT: 'ERI_TIMEOUT',                   // 504
    ERI_SERVICE_UNAVAILABLE: 'ERI_SERVICE_UNAVAILABLE', // 503

    // Finance / Payment
    PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',         // 402
    PAYMENT_FAILED: 'PAYMENT_FAILED',             // 402

    // ERI Specific
    UPSTREAM_ERROR: 'UPSTREAM_ERROR',             // 502
    UPSTREAM_SESSION_EXPIRED: 'UPSTREAM_SESSION_EXPIRED', // 401/502
    UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE', // 503
    FILING_ALREADY_SUBMITTED: 'FILING_ALREADY_SUBMITTED', // 409
    INVALID_PAN: 'INVALID_PAN',                   // 400
    INVALID_JSON: 'INVALID_JSON',                 // 400
    SUBMISSION_REJECTED: 'SUBMISSION_REJECTED',   // 422 - Alias for ERI_REJECTED

    // Document Import
    IMPORT_FILE_TOO_LARGE: 'IMPORT_FILE_TOO_LARGE',           // 413
    IMPORT_INVALID_FILE_TYPE: 'IMPORT_INVALID_FILE_TYPE',     // 400
    IMPORT_PARSE_FAILED: 'IMPORT_PARSE_FAILED',               // 422
    IMPORT_INVALID_SCHEMA: 'IMPORT_INVALID_SCHEMA',           // 422
    IMPORT_AY_MISMATCH: 'IMPORT_AY_MISMATCH',                 // 409
    IMPORT_PAN_MISMATCH: 'IMPORT_PAN_MISMATCH',               // 409
    IMPORT_ACCESS_DENIED: 'IMPORT_ACCESS_DENIED',             // 403
    IMPORT_RATE_LIMIT: 'IMPORT_RATE_LIMIT',                   // 429
    IMPORT_MALICIOUS_CONTENT: 'IMPORT_MALICIOUS_CONTENT',     // 400
    IMPORT_NOT_FOUND: 'IMPORT_NOT_FOUND',                     // 404
    IMPORT_FILING_NOT_DRAFT: 'IMPORT_FILING_NOT_DRAFT',       // 409
};
